extends Node

const UPGRADES = {
	"sword_slash1": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/sword.png",
		"display_name": "Sword",
		"description": "Slashes the enemy",
		"level": "LV 1",
		"type": "Weapon",
		"prerequisites": [],
	},
	"sword_slash2": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/sword.png",
		"display_name": "Sword",
		"description": "Slashes the enemy more often",
		"level": "LV 2",
		"type": "Weapon",
		"prerequisites": ["sword_slash1"],
	},
	"sword_slash3": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/sword.png",
		"display_name": "Sword",
		"description": "Slashes even more often",
		"level": "LV 3",
		"type": "Weapon",
		"prerequisites": ["sword_slash2"],
	},
	"sword_slash4": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/sword.png",
		"display_name": "Sword",
		"description": "Slashes even faster",
		"level": "LV 4",
		"type": "Weapon",
		"prerequisites": ["sword_slash3"],
	},
	"sword_slash5": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/sword.png",
		"display_name": "Sword",
		"description": "Martial Peak",
		"level": "LV 5",
		"type": "Weapon",
		"prerequisites": ["sword_slash4"],
	},
	"crescent_strike1": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Crescent Strike",
		"description": "Launch internal energy toward enemies",
		"level": "LV 1",
		"type": "Weapon",
		"prerequisites": [],
	},
	"crescent_strike2": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Crescent Strike",
		"description": "Increases attack frequency",
		"level": "LV 2",
		"type": "Weapon",
		"prerequisites": ["crescent_strike1"],
	},
	"crescent_strike3": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Crescent Strike",
		"description": "Launches an additional strike",
		"level": "LV 3",
		"type": "Weapon",
		"prerequisites": ["crescent_strike2"],
	},
	"crescent_strike4": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Crescent Strike",
		"description": "Attack even more often",
		"level": "LV 4",
		"type": "Weapon",
		"prerequisites": ["crescent_strike3"],
	},
	"crescent_strike5": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Crescent Strike",
		"description": "Even more",
		"level": "LV 5",
		"type": "Weapon",
		"prerequisites": ["crescent_strike4"],
	},
	"magic_circle1": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/magic_circle.png",
		"display_name": "Magic Circle",
		"description": "Creates a circle around, damaging all enemies within",
		"level": "LV 1",
		"type": "Weapon",
		"prerequisites": [],
	},
	"magic_circle2": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/magic_circle.png",
		"display_name": "Magic Circle",
		"description": "Increases circle radius",
		"level": "LV 2",
		"type": "Weapon",
		"prerequisites": ["magic_circle1"],
	},
	"magic_circle3": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/magic_circle.png",
		"display_name": "Magic Circle",
		"description": "Increases circle radius even more",
		"level": "LV 3",
		"type": "Weapon",
		"prerequisites": ["magic_circle2"],
	},
	"magic_circle4": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/magic_circle.png",
		"display_name": "Magic Circle",
		"description": "Damages enemies more often",
		"level": "LV 4",
		"type": "Weapon",
		"prerequisites": ["magic_circle3"],
	},
	"magic_circle5": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/magic_circle.png",
		"display_name": "Magic Circle",
		"description": "Increases circle radius even more",
		"level": "LV 5",
		"type": "Weapon",
		"prerequisites": ["magic_circle4"],
	},
	"health_regen1": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Health Regeneration",
		"description": "Regenerate 1% of Max Health every 5 seconds",
		"level": "LV 1",
		"type": "Stat",
		"prerequisites": [],
	},
	"health_regen2": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Health Regeneration",
		"description": "Regenerate 2% of Max Health every 5 seconds",
		"level": "LV 2",
		"type": "Stat",
		"prerequisites": ["health_regen1"],
	},
	"health_regen3": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Health Regeneration",
		"description": "Regenerate 3% of Max Health every 5 seconds",
		"level": "LV 3",
		"type": "Stat",
		"prerequisites": ["health_regen2"],
	},
	"health_regen4": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Health Regeneration",
		"description": "Regenerate 4% of Max Health every 5 seconds",
		"level": "LV 4",
		"type": "Stat",
		"prerequisites": ["health_regen3"],
	},
	"health_regen5": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Health Regeneration",
		"description": "Regenerate 5% of Max Health every 5 seconds",
		"level": "LV 5",
		"type": "Stat",
		"prerequisites": ["health_regen5"],
	},
	"max_health1": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Max Health",
		"description": "Increase Max Health by 10%",
		"level": "LV 1",
		"type": "Stat",
		"prerequisites": [],
	},
	"max_health2": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Max Health",
		"description": "Increase Max Health by 20%",
		"level": "LV 2",
		"type": "Stat",
		"prerequisites": ["max_health1"],
	},
	"max_health3": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Max Health",
		"description": "Increase Max Health by 30%",
		"level": "LV 3",
		"type": "Stat",
		"prerequisites": ["max_health2"],
	},
	"max_health4": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Max Health",
		"description": "Increase Max Health by 40%",
		"level": "LV 4",
		"type": "Stat",
		"prerequisites": ["max_health3"],
	},
	"max_health5": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Max Health",
		"description": "Increase Max Health by 50%",
		"level": "LV 5",
		"type": "Stat",
		"prerequisites": ["max_health5"],
	},
	"pickup_radius1": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Pickup Radius",
		"description": "Increases pickup radius by 40%",
		"level": "LV 1",
		"type": "Stat",
		"prerequisites": [],
	},
		"pickup_radius2": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Pickup Radius",
		"description": "Increases pickup radius by 80%",
		"level": "LV 2",
		"type": "Stat",
		"prerequisites": ["pickup_radius1"],
	},
		"pickup_radius3": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Pickup Radius",
		"description": "Increases pickup radius by 120%",
		"level": "LV 3",
		"type": "Stat",
		"prerequisites": ["pickup_radius2"],
	},
		"pickup_radius4": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Pickup Radius",
		"description": "Increases pickup radius by 160%",
		"level": "LV 4",
		"type": "Stat",
		"prerequisites": ["pickup_radius3"],
	},
		"pickup_radius5": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Pickup Radius",
		"description": "Increases pickup radius by 200%",
		"level": "LV 5",
		"type": "Stat",
		"prerequisites": ["pickup_radius4"],
	},
		"food": {
		"icon": "res://ProjectFallenKingdom/level_up/upgrade_icons/food.png",
		"display_name": "Food",
		"description": "Heals health by 20% of max health",
		"level": "",
		"type": "Healing",
		"prerequisites": [""],
	},
}
